version: "3.7"

services:

  app:

    volumes:

      - .:/gui_flask
      - pangia:/home/node/app

  rq-worker:

    volumes:

      - .:/gui_flask
      - pangia:/home/node/app

  redis:

    volumes:

      - .:/gui_flask

volumes:

  pangia: